name: apokalupsis_ui
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^5.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner 2.png
    - assets/images/thumbnail1.jpg
    - assets/images/thumbnail2.jpg
    - assets/images/thumbnail3.jpg
    - assets/images/thumbnail4.jpg
    - assets/images/thumbnail5.jpg
    - assets/images/thumbnail6.jpg
    - assets/images/thumbnail7.jpg
    - assets/images/thumbnail8.jpg
    - assets/images/profile_image.jpg
